### ISSUE TITLE
Use Vite instead of Create React App for boilerplate

### ISSUE THREAD

**Issue by max-programming** [mdbootstrap/mdb4-react-ui-kit#1]
I really liked how these UI components look and work like and I wanted to suggest something for the boilerplate download which happens here: 
![image](https://user-images.githubusercontent.com/51731966/117810289-d0944980-b27c-11eb-8b00-0c89baf05f59.png)

By default, it was created by Create React App, but there is something called [Vite](https://vitejs.dev/) which also has a scaffolding nature for React which is wayyyyy more faster than Create React App. The reason for that is using a different bundler.

I would love to contribute to this project and it'll be an honour if I helped in creating that boilerplate myself with Vite and help MDB React to use it ✌ 🎯

**Comment by krzysiu-w** [comment]
Thanks for this suggestion. We added it to our ideas :smiley: If there will be more requests about this - we will add a React package with Vite :fire: 

Keep coding!
