### ISSUE TITLE
Is this a new library or a new version of mdbreact?

### ISSUE THREAD

**Issue by Vrq** [mdbootstrap/mdb4-react-ui-kit#13]
When trying to find the mdbreact repository, I get redirected to this repo, so the questions are:
1. Is this a new version of mdbreact (if yes, then why not keeping up with semantic versioning?)
2. If it is a successor of mdbreact are there any breaking changes? What is the migration guide?
3. What happens with the old mdbreact library?

It seems that we are lacking some clear communication about what happened and this might confuse a lot of developers that use this library.

**Comment by bwsky-a** [comment]
Hello @Vrq , 
The repository this topic is in is MDB4 React, but we have another MDB5 React product available here - https://github.com/mdbootstrap/mdb-react-ui-kit

If you have any questions about the product, please send them to us at contact@mdbootstrap.com

**Comment by Vrq** [comment]
Is the new migration to the new library a breaking change?
Why have you changed the name of the repository without any communication?
Why not releasing Boostrap 5 React in version 6.x?
@smolenski-mikolaj I created the issue in the https://github.com/mdbootstrap/mdb-react-ui-kit repository, why have you moved it here?

**Comment by smolenski-mikolaj** [comment]
@Vrq we only chaged the names and paths to our repositories as we now recommend version 5 installation. Package.json names are the same as before, so all types of installation should work correctly (e.g. via npm). 

We didn't migrate. There are two different projects for MDB4 and MD5.

**Comment by Vrq** [comment]
Why haven't you created a seamless upgrade path from B4 to B5?
You could have created a 6.x version. 

With the current approach, we have to rename each import in the project from "mdbreact" to "mdb-react-ui-kit"...

**Comment by smolenski-mikolaj** [comment]
You will have to rename imports only if you want to migrate from MDB v4 to MDB v5. Please remember that such a migration is quite a complicated process due to the fact that these are two completely different projects. MDB v5 is not an ordinary continuation of MDB v4. This is a project written from scratch and each component has a lot of differences to version 4.
