### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by kdhttps** [mdbootstrap/mdb4-react-ui-kit#16]
Getting this warning when navigate link using `<MDBNavLink />`

![Screenshot from 2020-07-29 13-32-04](https://user-images.githubusercontent.com/39133739/88774029-926fe280-d1a0-11ea-95f8-ba27a3da3bd2.png)

**Comment by krzysiu-w** [comment]
Hi!

This warning will be fixed in the next release (22.11) :)
