### ISSUE TITLE
MDBBtn outline ripple is not visible

### ISSUE THREAD

**Issue by swayok** [mdbootstrap/mdb4-react-ui-kit#3]
Lets assume we have next button
```
<MDBBtn color="success" outline >
   text
</MDBBtn>
```

Expected behavior is that ripple will have any color except white. Perfectly - it should have `success` color,
You can see it yourself in docs: https://mdbootstrap.com/docs/b5/react/components/buttons/#section-outline

**Comment by Wojstan** [comment]
We will take a look at this issue in the current release. Thanks for Your report :)
