### ISSUE TITLE
MDBCarousel behavior is weird + bug in documentation

### ISSUE THREAD

**Issue by swayok** [mdbootstrap/mdb4-react-ui-kit#8]
1. Carousel with 1 slide magically slides to 2nd non-existing slide and then never slides again showing black screen
2. Carousel should have an option to disable autosliding at all - there are lots of stuations when autosliding is not needed (for example simple image gallery for shop item)
3. Carosuel prev and next buttons use font awesome. If font awesome is not used in project - icons are not shown. Maybe 2 props like 'nextIcon' and `prevIcon` can be added to allow customization.
4. In documentation `interval` is placed on `<MDBCarousel showControls interval={10000}>` while in reality `interval` prop should be placed on each `<MDBCarouselItem interval={10000}>`. I've verified the code of `MDBCarousel` and there are no interval prop or its usage there.
5. `MDBCarouselItem` should use `MDBCarousel`'s `interval` unless it has its own `interval`.

**Comment by Wojstan** [comment]
Unfortunately, MDBCarousel is causing some problems from the beginning. We plan to make huge changes in MDBCarousel in this or the next release. Thanks for reporting the issues.
