### ISSUE TITLE
Checkboxes are not aligned with the text when changing $font-size-base

### ISSUE THREAD

**Issue by rossille** [mdbootstrap/mdb4-react-ui-kit#9]
With the free theme, if I change the value of `$font-size-base` to `1.25rm`, checkboxes look a little bit offset from the text :

![image](https://user-images.githubusercontent.com/913658/129058671-7ac7d41d-fc94-45e6-89a6-87e288a87094.png)

I can think of two solutions to this problems (but I don't know which one is preferable in the general case) :

- Either scale the checkbox with the text
- Or work on the alignment so it stays on the baseline

**Possible workaround** : For now, I have achieved to implement the first solution in my own project by overriding the default values to take into account the text size. Maybe those would make better default values.

```scss
$form-check-input-margin-left: $font-size-base * 1.79;
$form-check-input-radio-margin-left: $font-size-base * 1.85;
$form-check-input-width-md: $font-size-base * 1.125;
$form-check-input-border-width: $font-size-base * 0.125;
$form-check-input-before-width: $font-size-base * 0.875;

$form-check-input-checkbox-border-radius: $font-size-base * 0.125;
$form-check-input-checkbox-focus-after-width: $font-size-base * 0.875;

$form-check-input-checkbox-checked-after-border-width: $font-size-base * 0.125;
$form-check-input-checkbox-checked-after-width: $font-size-base * 0.375;
$form-check-input-checkbox-checked-after-height: $font-size-base * 0.8125;
$form-check-input-checkbox-checked-after-margin-left: $font-size-base * 0.25;

$form-check-input-indeterminate-checked-after-border-width: $font-size-base * 0.125;
$form-check-input-indeterminate-checked-after-width: $font-size-base * 0.125;
$form-check-input-indeterminate-checked-after-height: $font-size-base * 0.875;
$form-check-input-indeterminate-checked-after-margin-left: $font-size-base 0.375;

$form-check-input-radio-width: $font-size-base * 1.25;

$form-check-input-radio-before-width: $font-size-base;
$form-check-input-radio-checked-after-width: $font-size-base * 0.625;
$form-check-input-radio-checked-after-margin-top: $font-size-base * 0.1875;
$form-check-input-radio-checked-after-margin-left: $font-size-base * 0.1875;
```

![image](https://user-images.githubusercontent.com/913658/129058451-e30ac9ac-a4c6-4276-bcb8-dd61f785dd20.png)

Also, thank you for making this awesome library available for free !

**Comment by Wojstan** [comment]
For now, we do not support changing the font size of the checkbox element. We will think about adding size property to scale checkbox. Thanks for using our library!
